from .ranked_insights import build_ranked_insights_view
from .consensus_conflicts import build_consensus_conflicts_view
from .system_status import build_system_status_view
from .performance_panel import build_performance_monitor_view